"""Package export for Aptiro: Markdown -> HTML -> DOCX -> PDF.

The provenance/exclusion gate runs in app._export_model BEFORE this
module ever sees the content: rejected, do-not-use, and unsupported
(red / live-unsupported / fabricated-metric) bullets are already
removed unless the user explicitly passed include_unsupported=True.

This module's only job is faithful rendering of the already-clean
model into each format. It NEVER invents content.
"""
import html as _html
import io

# Ordered by the build priority in the slice brief.
FORMATS = ["md", "html", "docx", "pdf"]

_SECTION_TITLES = {
    "summary": "Summary",
    "experience": "Experience",
    "skills": "Skills",
    "cover_letter": "Cover Letter",
}
_RESUME_SECTIONS = ["summary", "experience", "skills"]


class ExportError(Exception):
    pass


class ExportUnavailable(ExportError):
    """Raised when an optional renderer library is missing; the caller
    maps this to HTTP 501 so the app degrades instead of crashing."""


def _wanted_sections(artifact):
    if artifact == "cover_letter":
        return ["cover_letter"]
    if artifact == "both":
        return _RESUME_SECTIONS + ["cover_letter"]
    return _RESUME_SECTIONS


def _iter(model, artifact):
    for sec in _wanted_sections(artifact):
        items = model["sections"].get(sec) or []
        if items:
            yield sec, items


# --------------------------------------------------------------------------
# Markdown
# --------------------------------------------------------------------------
def _render_md(model, artifact):
    L = []
    L.append("# %s" % (model.get("title") or "Application Package"))
    L.append("")
    L.append("**Target:** %s @ %s  " % (model.get("job_title", ""),
                                        model.get("company", "")))
    L.append("**Fit:** %s/100" % model.get("score", 0))
    L.append("")
    for sec, items in _iter(model, artifact):
        L.append("## %s" % _SECTION_TITLES.get(sec, sec.title()))
        L.append("")
        if sec == "cover_letter":
            for it in items:
                L.append(it["text"])
                L.append("")
        else:
            for it in items:
                L.append("- %s" % it["text"])
            L.append("")
    if model.get("excluded") and not model.get("include_unsupported"):
        L.append("---")
        L.append("")
        L.append("> %d item(s) were excluded from this export "
                 "(unsupported or rejected) and are intentionally not "
                 "shown." % len(model["excluded"]))
        L.append("")
    L.append("<!-- Generated by Aptiro %s. Every line above traces to "
             "an approved source claim. -->" % model.get("generated_at",
                                                          ""))
    return ("\n".join(L)).encode("utf-8"), "md"


# --------------------------------------------------------------------------
# HTML
# --------------------------------------------------------------------------
_CSS = """
body{font:15px/1.55 -apple-system,Segoe UI,Roboto,Helvetica,Arial,
sans-serif;color:#1a1a1a;max-width:760px;margin:40px auto;padding:0 24px}
h1{font-size:24px;margin:0 0 4px}h2{font-size:15px;text-transform:uppercase;
letter-spacing:.06em;color:#444;border-bottom:1px solid #e3e3e3;
padding-bottom:4px;margin:26px 0 12px}.meta{color:#666;font-size:13px;
margin:0 0 8px}ul{margin:0;padding-left:20px}li{margin:4px 0}
.cl p{margin:0 0 12px}.foot{color:#999;font-size:11px;margin-top:32px;
border-top:1px solid #eee;padding-top:10px}
"""


def _render_html(model, artifact):
    e = _html.escape
    P = ['<!DOCTYPE html><html><head><meta charset="utf-8">',
         "<title>%s</title><style>%s</style></head><body>"
         % (e(model.get("title", "Application Package")), _CSS)]
    P.append("<h1>%s</h1>" % e(model.get("title", "")))
    P.append('<p class="meta">%s @ %s &middot; Fit %s/100</p>'
             % (e(model.get("job_title", "")), e(model.get("company", "")),
                model.get("score", 0)))
    for sec, items in _iter(model, artifact):
        P.append("<h2>%s</h2>" % e(_SECTION_TITLES.get(sec, sec.title())))
        if sec == "cover_letter":
            P.append('<div class="cl">')
            for it in items:
                P.append("<p>%s</p>" % e(it["text"]))
            P.append("</div>")
        else:
            P.append("<ul>")
            for it in items:
                P.append("<li>%s</li>" % e(it["text"]))
            P.append("</ul>")
    if model.get("excluded") and not model.get("include_unsupported"):
        P.append('<p class="foot">%d item(s) were excluded from this '
                 "export (unsupported or rejected).</p>"
                 % len(model["excluded"]))
    P.append('<p class="foot">Generated by Aptiro %s. Every line traces '
             "to an approved source claim.</p>"
             % e(model.get("generated_at", "")))
    P.append("</body></html>")
    return ("".join(P)).encode("utf-8"), "html"


# --------------------------------------------------------------------------
# DOCX
# --------------------------------------------------------------------------
def _render_docx(model, artifact):
    try:
        from docx import Document
        from docx.shared import Pt
    except Exception as e:                                # pragma: no cover
        raise ExportUnavailable(
            "python-docx is not installed; DOCX export unavailable (%s)."
            % e)
    doc = Document()
    style = doc.styles["Normal"]
    style.font.name = "Calibri"
    style.font.size = Pt(11)

    doc.add_heading(model.get("title", "Application Package"), level=0)
    meta = doc.add_paragraph()
    meta.add_run("%s @ %s  |  Fit %s/100"
                 % (model.get("job_title", ""), model.get("company", ""),
                    model.get("score", 0))).italic = True

    for sec, items in _iter(model, artifact):
        doc.add_heading(_SECTION_TITLES.get(sec, sec.title()), level=1)
        if sec == "cover_letter":
            for it in items:
                doc.add_paragraph(it["text"])
        else:
            for it in items:
                doc.add_paragraph(it["text"], style="List Bullet")

    if model.get("excluded") and not model.get("include_unsupported"):
        note = doc.add_paragraph()
        r = note.add_run(
            "%d item(s) were excluded from this export (unsupported or "
            "rejected)." % len(model["excluded"]))
        r.italic = True
    foot = doc.add_paragraph()
    fr = foot.add_run("Generated by Aptiro %s. Every line traces to an "
                      "approved source claim."
                      % model.get("generated_at", ""))
    fr.italic = True
    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue(), "docx"


# --------------------------------------------------------------------------
# PDF
# --------------------------------------------------------------------------
def _render_pdf(model, artifact):
    try:
        from reportlab.lib.pagesizes import LETTER
        from reportlab.lib.styles import getSampleStyleSheet, \
            ParagraphStyle
        from reportlab.lib.units import inch
        from reportlab.lib.enums import TA_LEFT
        from reportlab.platypus import (SimpleDocTemplate, Paragraph,
                                        Spacer, ListFlowable, ListItem)
    except Exception as e:                                # pragma: no cover
        raise ExportUnavailable(
            "reportlab is not installed; PDF export unavailable (%s)." % e)
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=LETTER,
                            topMargin=0.7 * inch, bottomMargin=0.7 * inch,
                            leftMargin=0.8 * inch, rightMargin=0.8 * inch)
    ss = getSampleStyleSheet()
    h1 = ParagraphStyle("Aptiro_H1", parent=ss["Title"], fontSize=20,
                        spaceAfter=4, alignment=TA_LEFT)
    meta = ParagraphStyle("Aptiro_meta", parent=ss["Normal"],
                          fontSize=9.5, textColor="#666666", spaceAfter=14)
    h2 = ParagraphStyle("Aptiro_H2", parent=ss["Heading2"], fontSize=12,
                        spaceBefore=14, spaceAfter=6, textColor="#222222")
    body = ParagraphStyle("Aptiro_body", parent=ss["Normal"],
                          fontSize=10.5, leading=15, spaceAfter=4)
    foot = ParagraphStyle("Aptiro_foot", parent=ss["Normal"], fontSize=8,
                          textColor="#999999", spaceBefore=20)

    def esc(s):
        return (s or "").replace("&", "&amp;").replace(
            "<", "&lt;").replace(">", "&gt;")

    flow = [Paragraph(esc(model.get("title", "Application Package")), h1),
            Paragraph("%s @ %s &nbsp;|&nbsp; Fit %s/100"
                      % (esc(model.get("job_title", "")),
                         esc(model.get("company", "")),
                         model.get("score", 0)), meta)]
    for sec, items in _iter(model, artifact):
        flow.append(Paragraph(_SECTION_TITLES.get(sec, sec.title()), h2))
        if sec == "cover_letter":
            for it in items:
                flow.append(Paragraph(esc(it["text"]), body))
        else:
            flow.append(ListFlowable(
                [ListItem(Paragraph(esc(it["text"]), body))
                 for it in items],
                bulletType="bullet", start="circle", leftIndent=14))
        flow.append(Spacer(1, 4))
    if model.get("excluded") and not model.get("include_unsupported"):
        flow.append(Paragraph(
            "%d item(s) were excluded from this export (unsupported or "
            "rejected)." % len(model["excluded"]), foot))
    flow.append(Paragraph(
        "Generated by Aptiro %s. Every line traces to an approved "
        "source claim." % esc(model.get("generated_at", "")), foot))
    doc.build(flow)
    return buf.getvalue(), "pdf"


_RENDERERS = {
    "md": _render_md, "html": _render_html,
    "docx": _render_docx, "pdf": _render_pdf,
}


def render(model, fmt, artifact="resume"):
    """Return (bytes, ext). model is the already provenance-filtered
    export model from app._export_model."""
    if fmt not in _RENDERERS:
        raise ExportError("Unsupported export format: %s" % fmt)
    return _RENDERERS[fmt](model, artifact)
